<?php

namespace ContainerCwsKxXk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControllerremoveFriendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ddvznpR.App\Controller\FriendshipController::removeFriend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ddvznpR'] ?? $container->load('get_ServiceLocator_DdvznpRService'));

        if (isset($container->privates['.service_locator.ddvznpR.App\\Controller\\FriendshipController::removeFriend()'])) {
            return $container->privates['.service_locator.ddvznpR.App\\Controller\\FriendshipController::removeFriend()'];
        }

        return $container->privates['.service_locator.ddvznpR.App\\Controller\\FriendshipController::removeFriend()'] = $a->withContext('App\\Controller\\FriendshipController::removeFriend()', $container);
    }
}
