<?php

namespace ContainerCwsKxXk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControlleruserProfileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oH993OF.App\Controller\FriendshipController::userProfile()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oH993OF.App\\Controller\\FriendshipController::userProfile()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.oH993OF.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.oH993OF": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\FriendshipController::userProfile()', $container);
    }
}
