<?php

namespace ContainerCwsKxXk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GroupManager' shared autowired service.
     *
     * @return \App\Service\GroupManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GroupManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\GroupManager'])) {
            return $container->privates['App\\Service\\GroupManager'];
        }

        return $container->privates['App\\Service\\GroupManager'] = new \App\Service\GroupManager($a);
    }
}
