<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \App\Entity\Projet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'intitule' => [parent::class, 'intitule', null],
        "\0".parent::class."\0".'nbPlaceMax' => [parent::class, 'nbPlaceMax', null],
        "\0".parent::class."\0".'nbPlaceMin' => [parent::class, 'nbPlaceMin', null],
        "\0".parent::class."\0".'voeux' => [parent::class, 'voeux', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'intitule' => [parent::class, 'intitule', null],
        'nbPlaceMax' => [parent::class, 'nbPlaceMax', null],
        'nbPlaceMin' => [parent::class, 'nbPlaceMin', null],
        'voeux' => [parent::class, 'voeux', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
