<?php

namespace ContainerHsPda1F;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZpmLbYSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZpmLbYS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZpmLbYS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'friendship' => ['privates', '.errored..service_locator.ZpmLbYS.App\\Entity\\Friendship', NULL, 'Cannot autowire service ".service_locator.ZpmLbYS": it needs an instance of "App\\Entity\\Friendship" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'security' => '?',
            'friendship' => 'App\\Entity\\Friendship',
            'entityManager' => '?',
        ]);
    }
}
