<?php

namespace ContainerHsPda1F;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControllerlistFriendsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqIEcZf.App\Controller\FriendshipController::listFriends()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.uqIEcZf'] ?? $container->load('get_ServiceLocator_UqIEcZfService'));

        if (isset($container->privates['.service_locator.uqIEcZf.App\\Controller\\FriendshipController::listFriends()'])) {
            return $container->privates['.service_locator.uqIEcZf.App\\Controller\\FriendshipController::listFriends()'];
        }

        return $container->privates['.service_locator.uqIEcZf.App\\Controller\\FriendshipController::listFriends()'] = $a->withContext('App\\Controller\\FriendshipController::listFriends()', $container);
    }
}
