<?php

namespace ContainerHsPda1F;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ONO5GRR.App\Controller\ProfilController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ONO5GRR.App\\Controller\\ProfilController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'voeuxRepository' => ['privates', 'App\\Repository\\VoeuxRepository', 'getVoeuxRepositoryService', true],
        ], [
            'voeuxRepository' => 'App\\Repository\\VoeuxRepository',
        ]))->withContext('App\\Controller\\ProfilController::index()', $container);
    }
}
