<?php

namespace ContainerAna6ptn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributionControllergenerateGroupsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._9UKmtu.App\Controller\AttributionController::generateGroups()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._9UKmtu.App\\Controller\\AttributionController::generateGroups()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupManager' => ['privates', 'App\\Service\\GroupManager', 'getGroupManagerService', true],
        ], [
            'groupManager' => 'App\\Service\\GroupManager',
        ]))->withContext('App\\Controller\\AttributionController::generateGroups()', $container);
    }
}
