<?php

namespace ContainerAna6ptn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControlleracceptFriendRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZpmLbYS.App\Controller\FriendshipController::acceptFriendRequest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ZpmLbYS'] ?? $container->load('get_ServiceLocator_ZpmLbYSService'));

        if (isset($container->privates['.service_locator.ZpmLbYS.App\\Controller\\FriendshipController::acceptFriendRequest()'])) {
            return $container->privates['.service_locator.ZpmLbYS.App\\Controller\\FriendshipController::acceptFriendRequest()'];
        }

        return $container->privates['.service_locator.ZpmLbYS.App\\Controller\\FriendshipController::acceptFriendRequest()'] = $a->withContext('App\\Controller\\FriendshipController::acceptFriendRequest()', $container);
    }
}
