<?php

namespace ContainerE9FeFw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControllerblockFriendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ddvznpR.App\Controller\FriendshipController::blockFriend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ddvznpR.App\\Controller\\FriendshipController::blockFriend()'] = ($container->privates['.service_locator.ddvznpR'] ?? $container->load('get_ServiceLocator_DdvznpRService'))->withContext('App\\Controller\\FriendshipController::blockFriend()', $container);
    }
}
