<?php

namespace ContainerE9FeFw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControllerunblockFriendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZpmLbYS.App\Controller\FriendshipController::unblockFriend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZpmLbYS.App\\Controller\\FriendshipController::unblockFriend()'] = ($container->privates['.service_locator.ZpmLbYS'] ?? $container->load('get_ServiceLocator_ZpmLbYSService'))->withContext('App\\Controller\\FriendshipController::unblockFriend()', $container);
    }
}
