<?php

namespace ContainerE9FeFw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipControllerlistBlockedFriendsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqIEcZf.App\Controller\FriendshipController::listBlockedFriends()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.uqIEcZf'] ?? $container->load('get_ServiceLocator_UqIEcZfService'));

        if (isset($container->privates['.service_locator.uqIEcZf.App\\Controller\\FriendshipController::listBlockedFriends()'])) {
            return $container->privates['.service_locator.uqIEcZf.App\\Controller\\FriendshipController::listBlockedFriends()'];
        }

        return $container->privates['.service_locator.uqIEcZf.App\\Controller\\FriendshipController::listBlockedFriends()'] = $a->withContext('App\\Controller\\FriendshipController::listBlockedFriends()', $container);
    }
}
