<?php

namespace ContainerE9FeFw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomePageControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5XBlwc3.App\Controller\HomePageController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5XBlwc3.App\\Controller\\HomePageController::index()'] = ($container->privates['.service_locator.5XBlwc3'] ?? $container->load('get_ServiceLocator_5XBlwc3Service'))->withContext('App\\Controller\\HomePageController::index()', $container);
    }
}
