<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAna6ptn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAna6ptn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAna6ptn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAna6ptn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAna6ptn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ana6ptn',
    'container.build_id' => '50be4f88',
    'container.build_time' => 1742492510,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAna6ptn');
